### ISSUE TITLE
Need to decide what to do with Ubuntu

### ISSUE THREAD

**Issue by daniviga** [gem/oq-python-dist#2]
- Ubuntu 14.04 does not have python 3.5, backport would be required like CentOS 7
- Ubuntu 16.04 has python 3.5
- Ubuntu 18.04 has python 3.6 (will require a different oq-libs)~~. python 3.5 availability to be checked.~~

**Comment by daniviga** [comment]
Ubuntu 18.04 does not provide Python 3.5 (Ubuntu does not provides multiple python3 as Fedora does).

Should we move to Python 3.6?
- Ubuntu < 18.04 and CentOS will have an `oq-python36` package,
- Ubuntu 18.04 will use its own Python 3.6.
- `oq-libs` will be based on Python 3.6

**Comment by micheles** [comment]
I am fine with moving to Python 3.6. AFAIK it already works. I would not rush things, though, it can go next year with the engine 3.0.

**Comment by daniviga** [comment]
>  I would not rush things, though, it can go next year with the engine 3.0.

Agreed, this was just a test on the feasibility and I created the repo to avoid loosing what I've done with it.

**Comment by daniviga** [comment]
We decided to have an oq-python35 package for all systems (Ubuntu and RHEL) regardless the upstream version.
